### ISSUE TITLE
Możliwość wklejania zdjęcia do wpisu, komentarza bezpośrednio ze schowka w trakcie pisania.

### ISSUE THREAD

**Issue by felixd** [Wykop-pl/Issues#1]
Brakuje mi od lat możliwości wklejenia zdjęcia w trakcie pisania komentarza, wpisu (bezpośrednio ze schowka).

**Comment by look997** [comment]
@felixd Zamknij ten issue jako dodany, bo już to dodali:
https://wykop.pl/wpis/76456883/tresc-zbanowanego-i-usunietego-przez-moderacje-zna

**Comment by felixd** [comment]
Fixed
