### ISSUE TITLE
Możliwość obserwacji i dostawania powiadomień, o każdej odpowiedzi do wpisu

### ISSUE THREAD

**Issue by look997** [Wykop-pl/Issues#22]
Możliwość obserwacji wpisu. Po prostu żeby widzieć każdy dodany do niego komentarz. Np. Jak masz swój wpis, i ci nie przychodzą powiadomienia jak ktoś nie zwraca się bezpośrednio do ciebie, albo czasem nie zwraca się do nikogo i nawet nikt nie wie, że ktoś napisał.
Zdarzyło mi się coś takiego i po czasie, przez przypadek, zauważyłem że jest jakaś odpowiedź, np. to 7 lat temu - https://wykop.pl/wpis/19398821/wykop-moderacja-zobaczcie-ta-sytuacje-http-www-wyk. Była nawet obietnica Moderacja - https://wykop.pl/wpis/19398821/wykop-moderacja-zobaczcie-ta-sytuacje-http-www-wyk#68995849

**Comment by wykopx** [comment]
O, to by się bardzo przydało!

**Comment by look997** [comment]
https://wykop.pl/wpis/77465161/nowosc-obserwowanie-dyskusji-na-wykopie-od-teraz-m

**Comment by wykopx** [comment]
Półtorej roku trzeba było czekać, ale w końcu im się udało 🍡
